name: test
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - ca-certificates
  - openssl
  - notebook
  - pip
  - certifi
  - matplotlib
  - pillow
  - pyyaml
  - requests
  - scipy
  - spacy
  - tqdm
  - pandas
  - seaborn
  - psutil
  - opencv
  - ftfy
  - regex
  - black
  - mypy
  - types-tqdm
  - types-pillow
  - types-setuptools
  - pip:
      - git+https://github.com/openai/CLIP.git
      - ultralytics
